const express = require('express');
const app = express();
const PORT = 3000;
let games = [
    {
        title: 'Persona 5',
        img: '.../assets/games/Persona 5',
        id: '1',
        players: '1',
        genre: 'Gioco di ruolo',
        price: '59,99€',
        platform: 'PS5',
        release: '31/3/2020',
        editor: 'SEGA EUROPE LTD',
        voices: 'Giapponese, Inglese',
        languages: 'Francese, Inglese, Italiano, Spagnolo, Tedesco',
        info: "Indossa la maschera. Mostra la tua verità. Preparati per un'esperienza GDR rinnovata su Persona®5 Royal, il più recente episodio della pluripremiata serie Persona®! Vesti la maschera di Joker e unisciti ai Ladri Fantasma di Cuori. Liberati dalle catene della società moderna e organizza colpi dentro le menti dei corrotti per risvegliare il loro cuore!",
    },
    {
        title: 'Persona 4',
        img: '.../assets/games/Persona 4',
        id: '2',
        players: '1',
        genre: 'Gioco di ruolo',
        price: '19,99€',
        platform: 'PS4',
        release: '19/1/2023',
        editor: 'SEGA EUROPE LTD',
        voices: 'Giapponese, Inglese',
        languages: 'Francese, Inglese, Italiano, Spagnolo, Tedesco',
        info: "Dicono che la tua anima gemella apparirà se fissi una televisione accesa in una notte piovosa... Una strana voce si diffonde nella cittadina di campagna di Inaba, nuova casa del protagonista, mentre inizia una serie di misteriosi omicidi. Man mano che il protagonista e i suoi compagni inseguiranno la verità, si ritroveranno ad aprire la porta verso un altro mondo.",
    },
    {
        title: 'Persona 3',
        img: '.../assets/games/Persona 3',
        id: '3',
        players: '1',
        genre: 'Gioco di ruolo',
        price: '19,99€',
        platform: 'PS4',
        release: '19/1/2023',
        editor: 'SEGA EUROPE LTD',
        voices: 'Giapponese, Inglese',
        languages: 'Francese, Inglese, Italiano, Spagnolo, Tedesco',
        info: "Poco dopo essersi trasferito al liceo Gekkoukan, il protagonista si imbatte nell'Ora Buia. Un'insolita calma avvolge la città, la gente si trasforma in inquietanti feretri e mostri sovrannaturali chiamati Ombre sciamano ovunque. Quando viene attaccato da una di queste Ombre e ogni speranza sembra ormai perduta, il potere del cuore, la sua Persona, si risveglia. orte del suo nuovo potere, va alla ricerca della verità sull'Ora Buia e affronta il destino che lo attende.",
    },
    {
        title: 'The Last of Us Parte II',
        img: '.../assets/games/TLOU2',
        id: '4',
        players: '1',
        genre: 'Azione, Avventura',
        price: '39,99€',
        platform: 'PS4',
        release: '19/6/2020',
        editor: 'Sony Interactive Entertainment Europe',
        voices: 'Francese, Greco, Inglese, Italiano, Polacco, Portoghese, Russo, Spagnolo, Tedesco, Turco',
        languages: 'Ceco, Croato, Danese, Finlandese, Francese, Greco, Inglese, Italiano, Norvegese, Olandese, Polacco, Portoghese, Russo, Spagnolo, Svedese, Tedesco, Turco, Ungherese',
        info: "Cinque anni dopo... Dopo un pericoloso viaggio attraverso gli Stati Uniti flagellati dalla pandemia, Ellie e Joel si stabiliscono in Wyoming. La vita in comunità garantisce loro una nuova stabilità, nonostante la costante minaccia degli infetti e dei sopravvissuti più disperati. Ma quando un inatteso evento compromette quegli equilibri, Ellie decide di intraprendere un nuovo viaggio. Questa volta per ottenere giustizia. La caccia ai responsabili, tuttavia, le riserverà strazianti ripercussioni fisiche ed emozionali.",
    },
    {
        title: 'The Last of Us Parte I',
        img: '.../assets/games/TLOU',
        id: '5',
        players: '1',
        genre: 'Azione',
        price: '79,99€',
        platform: 'PS5',
        release: '2/9/2022',
        editor: 'Sony Interactive Entertainment Europe',
        voices: 'Francese, Greco, Inglese, Italiano, Polacco, Portoghese, Russo, Spagnolo, Tedesco, Turco',
        languages: 'Ceco, Croato, Danese, Finlandese, Francese, Greco, Inglese, Italiano, Norvegese, Olandese, Polacco, Portoghese, Russo, Spagnolo, Svedese, Tedesco, Turco, Ungherese',
        info: "Rivivi l'indimenticabile esperienza di The Last of Us, vincitore di oltre 200 premi come Gioco dell'Anno, ora riprogrammato per console PlayStation®5. In una civiltà senza futuro, dove imperversano infetti e criminali, un uomo ormai segnato dalla vita, Joel, viene ingaggiato per condurre una ragazzina di 14 anni, Ellie, fino a una zona di quarantena militare. Ma quello che in principio sembra un incarico irrilevante, diventa presto un logorante viaggio attraverso gli Stati Uniti.",
    },
    {
        title: 'Bloodborne: Game of the Year Edition',
        img: '.../assets/games/Bloddyborny',
        id: '6',
        players: '1',
        genre: 'Gioco di ruolo',
        price: '34,99€',
        platform: 'PS4',
        release: '25/11/2015',
        editor: 'Sony Interactive Entertainment Europe',
        voices: 'Francese, Inglese, Italiano, Spagnolo, Tedesco',
        languages: 'Danese, Finlandese, Francese, Inglese, Italiano, Norvegese, Olandese, Polacco, Portoghese, Russo, Spagnolo, Svedese, Tedesco, Turco',
        info: "Un viandante solitario. Una città maledetta. Un mistero letale che annienta tutto ciò con cui entra in contatto. Affronta le tue paure addentrandoti nella desolata città di Yharnam, un luogo dimenticato, flagellato da una terribile piaga. Riuscirai a sopravvivere alla notte? La Game of the Year Edition include il contenuto scaricabile The Old Hunters, una nuova campagna della storia in cui scoprirai le vicende angoscianti dei cacciatori che, un tempo, resero Yharnam il loro parco giochi. Avrai accesso a numerosi costumi e armi trasformabili da aggiungere al tuo arsenale, incluso l'Arco affilato di Simon per una nuova esperienza di combattimento a distanza. Inoltre, gioca con gli incantesimi oscuri e trasformati in una bestia terrificante. Bentornato a Yharnam...",
    },
    {
        title: 'DARK SOULS: REMASTERED',
        img: '.../assets/games/DS',
        id: '7',
        players: '1',
        genre: 'Gioco di ruolo',
        price: '39,99€',
        platform: 'PS4',
        release: '25/5/2018',
        editor: 'BANDAI NAMCO ENTERTAINMENT EUROPE',
        voices: 'Inglese',
        languages: 'Francese (Francia), Inglese, Italiano, Polacco, Russo, Spagnolo, Tedesco',
        info: "E poi venne il Fuoco. Rivivi l'esperienza che ha rivoluzionato il mondo dei videogiochi e dato vita a un nuovo genere. Esplora la terra di Lordran in una splendida versione rimasterizzata in altissima definizione a 60 fps. Dark Souls Remastered include il gioco base e il DLC Artorias of the Abyss.",
    },
    {
        title: "Crash Bandicoot 4: It's About Time",
        img: '.../assets/games/Crash',
        id: '8',
        players: '1 - 4',
        genre: 'Azione',
        price: '69,99€',
        platform: 'PS5',
        release: '12/3/2021',
        editor: "Activision Blizzard Int'l BV",
        voices: 'Francese (Francia), Inglese, Italiano, Spagnolo, Tedesco',
        languages: 'Francese (Francia), Inglese, Italiano, Polacco, Russo, Spagnolo, Tedesco',
        info: "It's About Time - il nuovissimo gioco di Crash Bandicoot™! Parti per un'avventura oltre i confini del tempo in compagnia dei tuoi marsupiali preferiti. Neo Cortex e N. Tropy sono tornati e questa volta non hanno preso di mira solo questo universo, ma l'intero multiverso! Crash e Coco dovranno rimettere al loro posto le quattro maschere quantiche e piegare le leggi della realtà per salvare... gli universi! Nuove abilità? Ci sono. Più personaggi giocabili? Eccoli. Dimensioni alternative? Non potrebbero mancare. Boss improponibili? Sono già pronti. La solita, incredibile impertinenza? Ci puoi scommettere le mutande. Un secondo, sono davvero mutande? Non in questo universo!",
    },
    {
        title: 'DARK SOULS III - Deluxe Edition',
        img: '.../assets/games/DS3',
        id: '9',
        players: '1',
        genre: 'Azione, Avventura, Giochi Di Ruolo',
        price: '69,99€',
        platform: 'PS4',
        release: '12/4/2016',
        editor: 'BANDAI NAMCO ENTERTAINMENT EUROPE',
        voices: 'Inglese',
        languages: 'Francese (Francia), Inglese, Italiano, Polacco, Russo, Spagnolo, Tedesco',
        info: "La Deluxe Edition di DARK SOULS™ III include il gioco completo e il Season Pass. Espandi la tua esperienza di gioco con il Season Pass, che comprende nuove mappe, boss, nemici, armi e armature. Le fiamme si estinguono e il mondo è in rovina: esplora un universo ricco di nemici colossali e vaste ambientazioni. Preparati... e affronta nuovamente l'oscurità!",
    },
    {
        title: 'Horizon Forbidden West',
        img: '.../assets/games/Horizon',
        id: '10',
        players: '1',
        genre: 'Azione',
        price: '69,99€',
        platform: 'PS5',
        release: '18/2/2022',
        editor: 'Sony Interactive Entertainment Europe',
        voices: 'Giapponese, Inglese',
        languages: 'Arabo, Ceco, Cinese (semplificato), Cinese (tradizionale), Coreano, Danese, Finlandese, Francese (Francia), Giapponese, Greco, Inglese, Italiano, Norvegese, Olandese, Polacco, Portoghese (Brasile), Portoghese (Portogallo), Russo, Spagnolo, Spagnolo (Messico), Svedese, Tedesco, Thai, Turco, Ungherese',
        info: "Unisciti ad Aloy nell'esplorazione dell'Ovest Proibito, una pericolosa frontiera che nasconde nuove e misteriose minacce.",
    },
    {
        title: 'Gran Turismo 7',
        img: '.../assets/games/GT7',
        id: '11',
        players: '1 - 2',
        genre: 'Sport',
        price: '69,99€',
        platform: 'PS5',
        release: '4/3/2022',
        editor: 'Polyphony Digital Inc',
        voices: 'Non doppiato',
        languages: 'Arabo, Ceco, Francese (Francia), Giapponese, Greco, Inglese, Italiano, Olandese, Polacco, Portoghese (Portogallo), Russo, Spagnolo, Tedesco, Turco',
        info: "Vivi il simulatore di guida realistico completo e i suoi 25 anni di storia. Mettiti al volante di oltre 400 auto dal primo giorno: ogni modello, dai classici alle supercar più all'avanguardia, è realizzato con un livello di dettaglio senza precedenti. Affronta gli oltre 90 tracciati con condizioni climatiche dinamiche. Grazie al ritorno della leggendaria modalità GT Simulation puoi acquistare, mettere a punto e gareggiare nel corso della campagna per giocatore singolo man mano che sblocchi nuove auto e sfide. Se ami la competizione diretta, affina le tue abilità e gareggia nella modalità Sport. Piloti competitivi e occasionali, collezionisti, amanti della messa a punto, progettisti di livree e fotografi: tutti troveranno la loro traiettoria grazie alle fantastiche modalità di gioco offerte, incluse le popolari modalità campagna, Arcade e Accademia di guida.",
    },
    {
        title: 'FINAL FANTASY VII REMAKE INTERGRADE',
        img: '.../assets/games/FF7',
        id: '12',
        players: '1',
        genre: 'Gioco di ruolo',
        price: '79,99€',
        platform: 'PS5',
        release: '10/6/2021',
        editor: 'Square Enix LTD',
        voices: 'Francese (Francia), Giapponese, Inglese, Tedesco',
        languages: 'Francese (Francia), Inglese, Italiano, Portoghese (Brasile), Spagnolo, Tedesco',
        info: "INTERGRADE contiene FINAL FANTASY VII REMAKE, che ha ampliato i confini del gioco originale per PlayStation® rivisitandolo in modo spettacolare, e FF7R EPISODE INTERmission (nuovo episodio Yuffie). FINAL FANTASY VII REMAKE è la prima parte di un progetto più ampio e si conclude con la fuga da Midgar; FF7R EPISODE INTERmission (nuovo episodio Yuffie) si svolge a Midgar, dove la protagonista, insieme a un altro inviato di Wutai e con la collaborazione del nucleo originario dell'Avalanche, è in missione per infiltrarsi nel palazzo Shinra e impadronirsi della più potente materia mai esistita.",
    },
    {
        title: 'FINAL FANTASY XV ROYAL EDITION',
        img: '.../assets/games/FF15',
        id: '13',
        players: '1',
        genre: 'Giochi Di Ruolo, Azione, Avventura',
        price: '34,99€',
        platform: 'PS4',
        release: '6/3/2018',
        editor: 'Square Enix LTD',
        voices: 'Francese (Francia), Giapponese, Inglese, Tedesco',
        languages: 'Francese (Francia), Giapponese, Inglese, Italiano, Portoghese (Brasile), Russo, Spagnolo, Tedesco',
        info: "FINAL FANTASY XV ROYAL EDITION è la nuova vetta di una storia epica piena di contenuti aggiuntivi e novità. Unisciti al principe Noctis e ai suoi amici e lotta contro l'Impero per riconquistare il loro regno.",
    },
    {
        title: 'EA SPORTS FIFA 23 Standard Edition',
        img: '.../assets/games/Fifa',
        id: '14',
        players: '1 - 4',
        genre: 'Sport',
        price: '69,99€',
        platform: 'PS5',
        release: '30/9/2022',
        editor: 'EA Swiss Sarl',
        voices: 'Arabo, Inglese, Italiano',
        languages: 'Arabo, Inglese, Italiano, Tedesco',
        info: "Il gioco più bello del mondo scende in campo in EA SPORTS™ FIFA 23, con la FIFA World Cup™ maschile e femminile, l'aggiunta di squadre di club femminili e nuovi modi per giocare alle tue modalità preferite. Gioca la FIFA World Cup™ maschile ora disponibile in FIFA 23, con la FIFA World Cup™ femminile disponibile tramite aggiornamenti post lancio. Inoltre, scendi in campo per la prima volta con i club femminili e sfrutta le funzionalità cross-play che rende ancora più semplice giocare con gli amici. Goditi un nuovo modo di giocare e creare la rosa dei tuoi sogni con i Momenti FUT e un sistema di intesa rivisitato in FIFA Ultimate Team™, realizza i tuoi sogni calcistici nella modalità Carriera mentre definisci la tua personalità come giocatore, o vesti i panni di alcuni degli allenatori più famosi al mondo per replicarne i successi in panchina. Esprimi tutta la tua personalità in campo con VOLTA FOOTBALL e Pro Club, con nuovi livelli di personalizzazione e un gameplay migliorato nelle strade e negli stadi. Comunque tu scelga di giocare, divertiti con oltre 19.000 giocatori, più di 700 squadre, oltre 100 stadi e più di 30 tornei, comprese la UEFA Champions League, la Premier League e le nuove Barclays FA WSL e D1 Arkema francese, con un livello di realismo senza precedenti in FIFA 23.",
    },
    {
        title: 'God of War',
        img: '.../assets/games/GOW',
        id: '15',
        players: '1',
        genre: 'Azione, Avventura',
        price: '19,99€',
        platform: 'PS4',
        release: '4/10/2019',
        editor: 'Sony Interactive Entertainment Europe',
        voices: 'Francese (Francia), Inglese, Italiano, Tedesco',
        languages: 'Francese (Francia), Inglese, Italiano, Olandese, Tedesco, Turco',
        info: "Ora che vive come un semplice mortale, lontano dall'ombra degli dèi, Kratos deve adattarsi a terre sconosciute, inattesi pericoli e alla sua seconda possibilità di essere padre. Lui e suo figlio Atreus dovranno addentrarsi nel selvaggio regno di Midgard per vivere insieme una profonda avventura alla ricerca della propria realizzazione. Esplora un regno oscuro e in balia degli elementi, pieno di temibili creature uscite direttamente dalle pagine della mitologia norrena. Sconfiggi i tuoi nemici in feroci combattimenti ravvicinati che premiano la strategia e la precisione. Scopri la coinvolgente ed emozionante storia di un padre e un figlio e segui Kratos nel suo tentativo di tenere sotto controllo la rabbia che lo ha sempre caratterizzato",
    },
    {
        title: 'God of War Ragnarök',
        img: '.../assets/games/GOWR',
        id: '16',
        players: '1',
        genre: 'Azione',
        price: '79,99€',
        platform: 'PS5',
        release: '9/11/2022',
        editor: 'Sony Interactive Entertainment Europe',
        voices: 'Francese (Francia), Inglese, Italiano, Tedesco',
        languages: 'Arabo, Ceco, Cinese (semplificato), Cinese (tradizionale), Coreano, Croato, Francese (Francia), Giapponese, Greco, Inglese, Italiano, Olandese, Polacco, Portoghese (Brasile), Portoghese (Portogallo), Russo, Spagnolo, Tedesco, Thai, Turco, Ungherese',
        info: "Unisciti a Kratos e Atreus in un viaggio mitico alla ricerca di risposte prima che sopraggiunga il Ragnarök. Insieme, padre e figlio si spingeranno al limite nel corso del loro viaggio in ognuno dei nove regni. Attraverso paesaggi mitologici mozzafiato affronteranno terribili nemici come dèi norreni o mostri, preparandosi alla resa dei conti finale. In compagnia delle sue fidate armi, come il Leviatano e le Lame del caos, le abilità belliche di Kratos verranno messe alla prova come mai prima d’ora per proteggere la sua famiglia. Per lui e per Atreus è inoltre disponibile una serie di nuove abilità che permettono di affrontare combattimenti dinamici, emozionanti e altamente personalizzabili in questa epica avventura senza esclusione di colpi. Il tutto mentre le milizie di Asgard si preparano…",
    },
    {
        title: 'Sekiro: Shadows Die Twice - Game of the Year Edition',
        img: '.../assets/games/Sekiro',
        id: '17',
        players: '1',
        genre: 'Azione, Avventura',
        price: '34,99€',
        platform: 'PS4',
        release: '5/4/2019',
        editor: "Activision Blizzard Int'l BV",
        voices: 'Francese (Francia), Giapponese, Inglese, Italiano, Spagnolo, Tedesco',
        languages: 'Francese (Francia), Inglese, Italiano, Polacco, Russo, Spagnolo, Tedesco',
        info: "Esplora il Giappone alla fine del 1500, in pieno periodo Sengoku e affronta straordinari nemici in un mondo oscuro e perverso. Scatena protesi letali e potenti abilità ninja unendo azione furtiva, movimento verticale e combattimenti viscerali in un'avventura sanguinolenta. Vendicati. Riscatta il tuo onore. Uccidi con astuzia.",
    },
    {
        title: 'NieR: Automata Game of the YoRHa Edition',
        img: '.../assets/games/Nier',
        id: '18',
        players: '1',
        genre: 'Azione, Giochi Di Ruolo',
        price: '39,99€',
        platform: 'PS4',
        release: '26/2/2019',
        editor: 'Square Enix LTD',
        voices: 'Giapponese, Inglese',
        languages: 'Francese (Francia), Giapponese, Inglese, Italiano, Spagnolo, Tedesco',
        info: "Degli invasori provenienti da un altro pianeta sferrano un attacco improvviso con delle biomacchine. Nella speranza che annienti il nemico, la Resistenza introduce una nuova squadra di fanteria androide, gli YoRHa. L'acclamato e pluripremiato NieR:Automata™ è una nuova interpretazione del genere dei videogiochi di ruolo che mescola alla perfezione un'azione ipnotizzante e una storia affascinante.",
    },
    {
        title: 'Metro Exodus',
        img: '.../assets/games/Metro',
        id: '19',
        players: '1',
        genre: 'Azione, Avventura, Sparatutto',
        price: '29,99€',
        platform: 'PS5',
        release: '18/6/2021',
        editor: 'Deep Silver',
        voices: 'Francese (Francia), Inglese, Italiano, Russo, Spagnolo, Tedesco, Ucraino',
        languages: 'Ceco, Cinese (semplificato), Cinese (tradizionale), Coreano, Francese (Francia), Inglese, Italiano, Polacco, Russo, Spagnolo, Tedesco, Ucraino',
        info: "Metro Exodus è un epico sparatutto narrativo in prima persona firmato 4A Games. Il gioco combina combattimenti letali e furtività con esplorazione e survival horror in uno dei mondi più immersivi mai creati. Fuggi dalle rovine di una Mosca distrutta e intraprendi un viaggio epico nella Russia post-apocalittica per attraversare un intero continente nella più grande avventura della saga di Metro. Esplora le terre selvagge russe negli enormi livelli non lineari e segui un'emozionante storia ispirata ai romanzi di Dmitry Glukhovsky che dura un anno intero: primavera, estate e autunno, fino al profondo inverno nucleare.",
    },
    {
        title: 'MONSTER HUNTER: WORLD',
        img: '.../assets/games/MHW',
        id: '20',
        players: '1',
        genre: 'Azione',
        price: '19,99€',
        platform: 'PS4',
        release: '26/1/2018',
        editor: 'CE EUROPE LIMITED',
        voices: 'Francese (Francia), Giapponese, Inglese, Italiano, Spagnolo, Tedesco',
        languages: 'Arabo, Francese (Francia), Giapponese, Inglese, Italiano, Polacco, Portoghese (Brasile), Russo, Spagnolo, Tedesco',
        info: "Un nuovo mondo ti attende! Vesti i panni di un cacciatore e uccidi mostri feroci in un ecosistema rigoglioso, dove potrai sfruttare il paesaggio e i suoi abitanti per avere la meglio. Caccia da solo o in cooperativa con un massimo di altri tre giocatori: usa i materiali raccolti dai nemici abbattuti per forgiare un equipaggiamento migliore e lanciarti contro bestie ancora più grandi e selvagge!",
    },
    {
        title: 'Tales of Arise',
        img: '.../assets/games/ToA',
        id: '21',
        players: '1',
        genre: 'Gioco di ruolo',
        price: '69,99€',
        platform: 'PS5',
        release: '10/9/2021',
        editor: 'BANDAI NAMCO ENTERTAINMENT EUROPE',
        voices: 'Giapponese, Inglese',
        languages: 'Francese (Francia), Inglese, Italiano, Russo, Spagnolo, Tedesco',
        info: "Per trecento anni, Rena ha imposto il suo dominio su Dahna, saccheggiando le risorse del pianeta e mortificando la dignità e la libertà degli abitanti. Questo racconto ha inizio con l'incontro tra un ragazzo e una ragazza, nati su pianeti differenti ma entrambi determinati a cambiare il proprio destino e a costruire un nuovo futuro. Con un ricco cast di personaggi, un sistema di combattimento intuitivo e appagante e una storia coinvolgente ambientata in un mondo intriso di fascino, Tales of Arise porta ai massimi livelli il gioco di ruolo di scuola giapponese.",
    },
    {
        title: 'The Legend of Heroes: Trails of Cold Steel II',
        img: '.../assets/games/Trails 2',
        id: '22',
        players: '1',
        genre: 'Gioco di ruolo',
        price: '39,99€',
        platform: 'PS4',
        release: '7/6/2019',
        editor: 'Marvelous Europe Limited',
        voices: 'Giapponese, Inglese',
        languages: 'Inglese',
        info: "Dopo una terribile battaglia, il cadetto Rean Schwarzer si risveglia tra le montagne solo e ignaro di quello che è accaduto ai suoi compagni e commilitoni. Pur sapendo che lo attende un arduo cammino, Rean decide di sguainare di nuovo la sua spada e di partire alla ricerca dei suoi amici e di un modo per mettere fine alla guerra prima che sia troppo tardi...",
    },
    {
        title: 'The Legend of Heroes: Trails of Cold Steel III',
        img: '.../assets/games/Trails 3',
        id: '23',
        players: '1',
        genre: 'Gioco di ruolo',
        price: '59,99€',
        platform: 'PS4',
        release: '22/10/2019',
        editor: 'NIS America',
        voices: 'Giapponese, Inglese',
        languages: 'Francese (Francia), Inglese',
        info: "Rean Schwarzer scopre un oscuro complotto che minaccia la sua patria. Per affrontare i nemici, dovrà fare da istruttore in un nuovo campus e preparare una nuova generazione di eroi da guidare verso la vittoria.",
    },
    {
        title: 'The Legend of Heroes: Trails of Cold Steel IV',
        img: '.../assets/games/Trails 4',
        id: '24',
        players: '1',
        genre: 'Gioco di ruolo',
        price: '59,99€',
        platform: 'PS4',
        release: '27/10/2020',
        editor: 'SEGA EUROPE LTD',
        voices: 'Giapponese, Inglese',
        languages: 'Giapponese, Inglese',
        info: "L'attesissimo finale dell'epica storia di un continente giunge al culmine nel capitolo finale della saga di Trails of Cold Steel! È LA GUERRA! Il continente di Zemuria è trascinato in un conflitto mentre l'Erebonian Empire mobilita le sue forze militari per intero. Gli eroi di Class VII, sia i vecchi sia i nuovi, devono unirsi per porre fine al conflitto prima che esso consumi il continente.",
    },
]

app.use((req, res, next) => {
    res.header('Access-Control-Allow-Origin', '*');
    next();
  });

app.get('/', (req, res) =>{
    res.send(games);
});

app.listen(PORT, () =>{
    console.log("server live");
});